/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
    1: 1
    3: 1,3
    6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
*/

#include <stdio.h>
#include <math.h>

int get_num_of_factors(int number);

int main()
{
    int triangle_number = 0;
    int i = 1;
    int target = 500;

    while(1)
    {
        triangle_number += i;
        i++;

        if (get_num_of_factors(triangle_number) >= target)
        {
            break;
        }
    }

    printf("Answer: %d\n", triangle_number);
    
    return 0;
}

int get_num_of_factors(int number)
{
    int limit = number / 2;
    int count = 2;
    int i = 2;

    if (number == 1)
    {
        return 1;
    }

    while(1)
    {
    
        if (number % i == 0)
        {
            count += 2;
        }

        if (i >= (int)sqrt(number))
        {
            break;
        }

        if (number/i == (int)sqrt(number) + 1)
        {
            count++;
            break;
        }

        i++;

    }

    return count;
}