/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

typedef struct 
{
    int *array;
    size_t used;
    size_t size;

} Array;

void initialize_array(Array *array, size_t initial_size);
void insert(Array *array, int element);
void resize(Array *array);
void free_array(Array *array);

int main()

{
    Array fibo_sequence;
    initialize_array(&fibo_sequence, 2);

    insert(&fibo_sequence, 1);
    insert(&fibo_sequence, 2);

    int limit = 4 * pow(10, 6);
    int next_element = 0;
    int sum = 0;

    while (next_element <= limit)
    {
        next_element = fibo_sequence.array[fibo_sequence.used - 1] + fibo_sequence.array[fibo_sequence.used -2];
        insert(&fibo_sequence, next_element);
    }

    
    for (int i = 0; i < fibo_sequence.used; i++)
    {
        if (fibo_sequence.array[i] % 2 == 0)
        {
            sum += fibo_sequence.array[i];
        }
    }
    printf("sum: %d\n", sum);

    free_array(&fibo_sequence);

    return 0;
}


void initialize_array(Array *array, size_t initial_size)
{
    array->array = malloc(initial_size * sizeof(int));
    array->used = 0;
    array->size = initial_size;
}


void insert(Array *array, int element)
{
    if (array->used == array->size)
    {
        resize(array);
    }

    array->array[array->used++] = element;
}


void resize(Array *array)
{
    array->size *= 2;
    array->array = realloc(array->array, array->size * sizeof(int));
}


void free_array(Array *array)
{
    free(array->array);
    array->array = NULL;
    array->used = array->size = 0;
}