/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>
#include <math.h>

int main()

{
    int limit = 4 * pow(10, 6);
    int last = 2;
    int penultimate = 1;
    int next_element = 0;
    int sum = 2;


    while (next_element <= 4000000)
    {
        next_element = last + penultimate;
        penultimate = last;
        last = next_element;

        if (next_element % 2 == 0)
        {
            sum += next_element;
        }
    }

    printf("sum: %d\n", sum);


    return 0;
}
